package entidades;
// Generated 14/07/2019 10:33:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atencion generated by hbm2java
 */
public class Atencion  implements java.io.Serializable {


     private int idAtencion;
     private Personal personal;
     private Date fechaAtencion;
     private String diagnostico;
     private Date horaAtencion;
     private int idMascota;
     private int codigoCliente;

    public Atencion() {
    }

	
    public Atencion(int idAtencion, Personal personal, Date fechaAtencion, String diagnostico, int idMascota, int codigoCliente) {
        this.idAtencion = idAtencion;
        this.personal = personal;
        this.fechaAtencion = fechaAtencion;
        this.diagnostico = diagnostico;
        this.idMascota = idMascota;
        this.codigoCliente = codigoCliente;
    }
    public Atencion(int idAtencion, Personal personal, Date fechaAtencion, String diagnostico, Date horaAtencion, int idMascota, int codigoCliente) {
       this.idAtencion = idAtencion;
       this.personal = personal;
       this.fechaAtencion = fechaAtencion;
       this.diagnostico = diagnostico;
       this.horaAtencion = horaAtencion;
       this.idMascota = idMascota;
       this.codigoCliente = codigoCliente;
    }
   
    public int getIdAtencion() {
        return this.idAtencion;
    }
    
    public void setIdAtencion(int idAtencion) {
        this.idAtencion = idAtencion;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public Date getHoraAtencion() {
        return this.horaAtencion;
    }
    
    public void setHoraAtencion(Date horaAtencion) {
        this.horaAtencion = horaAtencion;
    }
    public int getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(int idMascota) {
        this.idMascota = idMascota;
    }
    public int getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(int codigoCliente) {
        this.codigoCliente = codigoCliente;
    }




}


