package entidades;
// Generated 14/07/2019 10:33:56 PM by Hibernate Tools 4.3.1



/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private int idVacuna;
     private String nombreVacuna;
     private String enfermedad;
     private String tipoVacuna;

    public Vacuna() {
    }

    public Vacuna(int idVacuna, String nombreVacuna, String enfermedad, String tipoVacuna) {
       this.idVacuna = idVacuna;
       this.nombreVacuna = nombreVacuna;
       this.enfermedad = enfermedad;
       this.tipoVacuna = tipoVacuna;
    }
   
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public String getNombreVacuna() {
        return this.nombreVacuna;
    }
    
    public void setNombreVacuna(String nombreVacuna) {
        this.nombreVacuna = nombreVacuna;
    }
    public String getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(String enfermedad) {
        this.enfermedad = enfermedad;
    }
    public String getTipoVacuna() {
        return this.tipoVacuna;
    }
    
    public void setTipoVacuna(String tipoVacuna) {
        this.tipoVacuna = tipoVacuna;
    }




}


